JCF: clean up the repo by removing scripts which are no longer in use
DUNE-DAQ/daq-release pull request #290
Opened 2023-07-21 02:00 UTC by jcfreeman2

I've removed the following scripts in this PR for the following reasons. When reviewing, please let me know if there are any I should un-remove:
* `scripts/merge-to-master.sh`: we don't use `master` branches anymore in our git workflow
* `scripts/delete-release-tag.sh`: apparently deleting `rc-dunedaq-v3.0.0-5` is the last time this was used, over a year ago
* `scripts/install-cvmfs-ubuntu.sh`: dating from 2020, I don't _think_ this is used anymore
* `scripts/create-cvmfs-dbt.sh`: last edited April 2022, this refers to a directory called `/home/dingpf/cvmfs_dunedaq/tools/`
* `scripts/spack/get-commit-hash.sh`: contains the comment `This file is for generating YAML entries of DAQ packages from old release_manifest.sh`, long behind us by now
* `scripts/spack/spack-views.sh`: dating from the early days of our Spack development, and no longer used

2023-07-22 00:45 UTC, dingp requested changes
It might be worth to keep `create-cvmfs-dbt.sh`. Maybe move it to the `cvmfs` subdirectory?

2023-07-22 00:45 UTC, dingp commented on scripts/create-cvmfs-dbt.sh
You may want to keep this script. It is used to create the `/tools/dbt` directory from scratch. It creates subdirectories of each tagged version of `vX.Y.Z` and then create symlinks of release tags, and point those to the subdirectories of versioned tag.

2023-07-22 01:40 UTC, jcfreeman2 commented
`create-cvmfs-dbt.sh` has been brought back in to the location requested.

2023-07-26 06:29 UTC, dingp approved these changes

2023-07-27 03:45 UTC, merged